steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["clean","install"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/1/cb-hackathon", "--build-arg=JAR_FILE=/root/.m2/repository/com/cb/covid/Covid19_Infected_Cases/0.0.1-SNAPSHOT/Covid19_Infected_Cases-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/1/cb-hackathon"]
